### ISSUE TITLE
Domain Sharding / Multiple CDN Host Names

### ISSUE THREAD

**Issue by jaswsinc** [websharks/zencache-kb#71]
---
##### KB Article Creation Checklist

- [ ] Write initial draft for this KB Article; label this issue `draft` and either `questions` or `tutorials`
- [ ] Add [required YAML configuration](https://github.com/websharks/team/wiki/KB-Articles-::-Required-YAML-Configuration)
- [ ] Add Tags for this KB Article to the YAML config (see [YAML Keys (Explained)](https://github.com/websharks/team/wiki/KB-Articles-::-Required-YAML-Configuration#yaml-keys-explained))
- [ ] Edit and finalize draft for publishing (remove `draft` label, add `draft-finalized` label)
- [ ] Assign Issue to yourself and [create Markdown file](https://github.com/websharks/team/wiki/KB-Articles-::-Creating-the-Markdown-File) (remove `draft-finalized` label, add `pending`)
- [ ] Project Lead: Review and Publish KB Article (remove `pending` label, add `published` label)

##### Additional TODOs

_Additional TODO list items go here._

```yaml
title: Domain Sharding / Multiple CDN Host Names
categories: tutorials
tags: 
author: jaswsinc
github-issue: 
```
---

## TODO

[This article should be about Domain Sharding].

Referencing: https://github.com/websharks/zencache-pro/pull/116
See also: http://gtmetrix.com/parallelize-downloads-across-hostnames.html
See also: https://www.maxcdn.com/one/visual-glossary/domain-sharding-2/
